language: c
sudo: required

env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06

os:
  - linux
  - osx

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

before_script:
  - bash -ex .travis-opam.sh
  - make build

script:
  - make test
